/**
 * Sample drone flight data for demo purposes
 */
export const sampleFlights = [
  {
    id: 1,
    title: "Sunset Over Big Sur Cliffs",
    pilot: "SkyView Alex",
    location: "Big Sur, California",
    lat: 36.2704,
    lng: -121.8081,
    description: "Golden hour flight along the dramatic coastline of Big Sur. 400ft altitude.",
    tags: ["sunset", "coastline", "california", "cliffs"],
    category: "coastal",
    views: 12453,
    likes: 892,
    date: "2026-03-28",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 2,
    title: "Manhattan Skyline at Dawn",
    pilot: "UrbanWings",
    location: "New York City, New York",
    lat: 40.7128,
    lng: -74.006,
    description: "Pre-sunrise flight over lower Manhattan.",
    tags: ["urban", "skyline", "sunrise", "manhattan"],
    category: "urban",
    views: 28901,
    likes: 2340,
    date: "2026-03-25",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 3,
    title: "Banff National Park",
    pilot: "NorthernDrone",
    location: "Banff, Alberta, Canada",
    lat: 51.4968,
    lng: -115.9281,
    description: "Flying over the turquoise waters of Moraine Lake.",
    tags: ["mountains", "lake", "canada", "nature"],
    category: "mountain",
    views: 18762,
    likes: 1560,
    date: "2026-03-20",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 4,
    title: "Santorini Blue Domes",
    pilot: "MediterraneanFly",
    location: "Santorini, Greece",
    lat: 36.3932,
    lng: 25.4615,
    description: "Orbiting the iconic blue-domed churches of Oia at sunset.",
    tags: ["santorini", "greece", "sunset", "architecture"],
    category: "sunset",
    views: 34211,
    likes: 4102,
    date: "2026-03-18",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 5,
    title: "Amazon Rainforest Canopy",
    pilot: "JunglePilot",
    location: "Manaus, Brazil",
    lat: -3.119,
    lng: -60.0217,
    description: "Skimming the top of the rainforest canopy at dawn.",
    tags: ["amazon", "rainforest", "nature", "brazil"],
    category: "nature",
    views: 9834,
    likes: 721,
    date: "2026-03-15",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 6,
    title: "Dubai Marina Night Flight",
    pilot: "GulfSkyOps",
    location: "Dubai, UAE",
    lat: 25.0657,
    lng: 55.1713,
    description: "Night flight through the illuminated towers of Dubai Marina.",
    tags: ["dubai", "night", "urban", "lights"],
    category: "urban",
    views: 45120,
    likes: 5230,
    date: "2026-03-12",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 7,
    title: "Iceland Northern Lights",
    pilot: "ArcticDrone",
    location: "Reykjavik, Iceland",
    lat: 64.1466,
    lng: -21.9426,
    description: "Drone hovering at 200ft capturing the aurora borealis.",
    tags: ["iceland", "aurora", "night", "nature"],
    category: "nature",
    views: 67890,
    likes: 8900,
    date: "2026-03-10",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 8,
    title: "Great Barrier Reef Aerial",
    pilot: "CoralSkyAU",
    location: "Cairns, Australia",
    lat: -16.9186,
    lng: 145.7781,
    description: "Flying over the world's largest coral reef system.",
    tags: ["reef", "ocean", "australia", "nature"],
    category: "coastal",
    views: 23456,
    likes: 1890,
    date: "2026-03-08",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 9,
    title: "Machu Picchu Sunrise",
    pilot: "AndesFlight",
    location: "Cusco, Peru",
    lat: -13.1631,
    lng: -72.545,
    description: "First light hitting the ancient Incan citadel.",
    tags: ["peru", "ruins", "sunrise", "mountains"],
    category: "mountain",
    views: 31000,
    likes: 3450,
    date: "2026-03-05",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 10,
    title: "Tokyo Shibuya Crossing",
    pilot: "TokyoDroneCo",
    location: "Tokyo, Japan",
    lat: 35.6595,
    lng: 139.7004,
    description: "Overhead shot of the world's busiest intersection.",
    tags: ["tokyo", "urban", "crossing", "japan"],
    category: "urban",
    views: 55670,
    likes: 6780,
    date: "2026-03-01",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 11,
    title: "Sahara Desert Dunes",
    pilot: "DesertHawk",
    location: "Merzouga, Morocco",
    lat: 31.0802,
    lng: -4.0128,
    description: "Sweeping over the Erg Chebbi dunes at golden hour.",
    tags: ["sahara", "desert", "morocco", "landscape"],
    category: "landscape",
    views: 14500,
    likes: 1100,
    date: "2026-02-28",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 12,
    title: "Norwegian Fjords",
    pilot: "NordicAir",
    location: "Geiranger, Norway",
    lat: 62.1008,
    lng: 7.094,
    description: "Threading through the dramatic Geirangerfjord.",
    tags: ["norway", "fjords", "nature", "water"],
    category: "landscape",
    views: 21340,
    likes: 2890,
    date: "2026-02-25",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 13,
    title: "Redondo Beach Pier Sunset",
    pilot: "SoCalDrone",
    location: "Redondo Beach, California",
    lat: 33.8492,
    lng: -118.3884,
    description: "Local flight over the Redondo Beach pier at sunset.",
    tags: ["redondo", "beach", "sunset", "california", "pier"],
    category: "sunset",
    views: 8900,
    likes: 670,
    date: "2026-03-30",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 14,
    title: "Victoria Falls Aerial",
    pilot: "AfricaSkyOps",
    location: "Victoria Falls, Zimbabwe",
    lat: -17.9244,
    lng: 25.8567,
    description: "Drone flight over the world's largest waterfall.",
    tags: ["waterfall", "africa", "nature", "zimbabwe"],
    category: "nature",
    views: 19800,
    likes: 2100,
    date: "2026-02-20",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 15,
    title: "Bali Rice Terraces",
    pilot: "IslandDrone",
    location: "Ubud, Bali, Indonesia",
    lat: -8.5069,
    lng: 115.2625,
    description: "Morning flight over UNESCO Tegallalang rice terraces.",
    tags: ["bali", "rice", "terraces", "indonesia"],
    category: "landscape",
    views: 27600,
    likes: 3200,
    date: "2026-02-15",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 16,
    title: "Hollywood Sign Flyover",
    pilot: "LADroneKing",
    location: "Hollywood, Los Angeles",
    lat: 34.1341,
    lng: -118.3215,
    description: "Iconic aerial pass over the Hollywood sign.",
    tags: ["hollywood", "losangeles", "urban", "iconic"],
    category: "urban",
    views: 41200,
    likes: 5100,
    date: "2026-03-29",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 17,
    title: "Venice Beach Boardwalk",
    pilot: "WestsideFPV",
    location: "Venice Beach, Los Angeles",
    lat: 33.985,
    lng: -118.4695,
    description: "Low altitude cruise over the Venice Beach boardwalk.",
    tags: ["venice", "beach", "losangeles", "boardwalk"],
    category: "coastal",
    views: 18700,
    likes: 2300,
    date: "2026-03-27",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 18,
    title: "DTLA Skyline at Dusk",
    pilot: "SkylineLA",
    location: "Downtown Los Angeles",
    lat: 34.0522,
    lng: -118.2437,
    description: "Golden hour circling downtown LA skyscrapers.",
    tags: ["downtown", "losangeles", "skyline", "sunset"],
    category: "urban",
    views: 33500,
    likes: 4200,
    date: "2026-03-24",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 19,
    title: "Santa Monica Pier Night",
    pilot: "NightFlyLA",
    location: "Santa Monica, Los Angeles",
    lat: 34.0094,
    lng: -118.4973,
    description: "The ferris wheel lit up in neon from above.",
    tags: ["santamonica", "pier", "night", "losangeles"],
    category: "urban",
    views: 22100,
    likes: 3400,
    date: "2026-03-22",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 20,
    title: "Griffith Observatory Sunrise",
    pilot: "LADroneKing",
    location: "Griffith Park, Los Angeles",
    lat: 34.1185,
    lng: -118.3004,
    description: "First light hitting Griffith Observatory.",
    tags: ["griffith", "observatory", "sunrise", "losangeles"],
    category: "landscape",
    views: 29800,
    likes: 3900,
    date: "2026-03-19",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 21,
    title: "Malibu Coast Highway",
    pilot: "PCHPilot",
    location: "Malibu, California",
    lat: 34.0259,
    lng: -118.7798,
    description: "Following PCH from above with surfers below.",
    tags: ["malibu", "pch", "coast", "california"],
    category: "coastal",
    views: 15600,
    likes: 1800,
    date: "2026-03-16",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 22,
    title: "LAX Approach Angle",
    pilot: "AvGeekDrone",
    location: "Los Angeles International Airport",
    lat: 33.9425,
    lng: -118.4081,
    description: "Planes on final approach to LAX with the ocean behind.",
    tags: ["lax", "airport", "planes", "losangeles"],
    category: "urban",
    views: 52300,
    likes: 7100,
    date: "2026-03-13",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 23,
    title: "Palos Verdes Cliffs",
    pilot: "SoCalDrone",
    location: "Palos Verdes, California",
    lat: 33.7444,
    lng: -118.387,
    description: "Dramatic cliffs with Catalina Island in the distance.",
    tags: ["palosverdes", "cliffs", "ocean", "california"],
    category: "coastal",
    views: 11200,
    likes: 1400,
    date: "2026-03-11",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 24,
    title: "Rose Bowl Aerial",
    pilot: "SGVDrone",
    location: "Pasadena, California",
    lat: 34.1613,
    lng: -118.1676,
    description: "Overhead view of the Rose Bowl stadium.",
    tags: ["rosebowl", "pasadena", "stadium", "california"],
    category: "landscape",
    views: 13700,
    likes: 1600,
    date: "2026-03-09",
    thumbnail: "",
    videoUrl: ""
  },
  {
    id: 25,
    title: "Long Beach Harbor",
    pilot: "PortDrone",
    location: "Long Beach, California",
    lat: 33.754,
    lng: -118.216,
    description: "One of America's busiest ports from above.",
    tags: ["longbeach", "harbor", "port", "california"],
    category: "urban",
    views: 9400,
    likes: 980,
    date: "2026-03-06",
    thumbnail: "",
    videoUrl: ""
  }
];
